spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    
  jpa: 
    properties:
      hibernate:
        show_sql: true
        
    hibernate:
        ddl-auto: update
    defer-datasource-initialization: true   
  mail:
    host: smtp.gmail.com
    port: 587
    username: akpanigrahi.2k8@gmail.com
    password: Jayanti@2212
    properties:
      mail:
      smtp:
        starttls:
          enable: true
        auth: true
                
       